# 
# EnderMail installation:
# 
# - Requires AuthMe working with MySQL, a plugin like this would have no sense without authentication
# - Create EnderMail tables in same database as AuthMe for access on querying existing users
# - Copy MySQL AuthMe configurations to datasource section below in this file for same reason
# - Edit this line in AuthMe config.yml to do a mail check on players login:
# 
# forceCommands: [mail check quiet]
# 
# 
# MySQL tables creation:
# 
# CREATE TABLE `endermail_messages` (
# 	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
# 	`mfrom` TEXT NOT NULL,
# 	`mto` TEXT NOT NULL,
# 	`sent` DATETIME NOT NULL,
# 	`subject` TEXT NOT NULL,
# 	`brief` TEXT NOT NULL,
# 	`message` TEXT NOT NULL,
# 	`attachment` TEXT NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 
# CREATE TABLE `endermail_folders` (
# 	`muser` TEXT NOT NULL,
# 	`folder` TINYINT UNSIGNED NOT NULL,
# 	`unread` TINYINT UNSIGNED NOT NULL,
# 	`id` INT UNSIGNED NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 
# 
# A message to the server admin (my colleague)
# 
# hi, when i installed my server and play with my friends i missed 2 things:
# 
# 1 - a way to send items to the distance:
# sometimes i was crafting or building something and asked somebody for materials
# and they said me "yes i am plenty of <material>"
# so i answered "great!, can you give me some?"
# and they told me "sure, but i am busy now and i am at <30 kilometers far>"
# that is for i installed mailitems, but now it seems outdated
# 
# 2 - a way to send offline messages:
# my server is friend based, has a low population and everybody knows each other,
# sometimes i was exploring and found some material i remembered a friend needed
# so i felt bad because i could not tell him because he was offline
# so i searched for some mail plugins, but none satisfied me
# 
# so instead of still searching some decent plugins, i decided to write my own and share with you
# 
# i tried to make this plugin the most fiendly and intuitive possible, mostly are inspired on linux mail and sendmail commands.
# after weeks breaking my head i finally found a decent way to make text links, a huge interface improvement
# but since maybe you don't have a mouse, all subcommands can also be typed (full or just uppercases, ie.: ReplyAll -> ra)
# 
# that all for now, i hope you enjoy this plugin and contact me at project page if have some bug report or suggestion
# thanks for using this plugin and happy crafting
# 


# edit these configurations copying from AuthMe config.yml
DataSource:
  mySQLHost: localhost
  mySQLPort: 3306
  mySQLDatabase: database
  mySQLUsername: dbuser
  mySQLPassword: dbpass
  mySQLTablename: table
  mySQLRealName: playername
  mySQLColumnLastLogin: lastlogin

# ticks in which plugin will remember last folder, message or entered line,
# for browsing, viewing and composing (default 2400 = 2min)
expire: 2400
