# 
# EnderMail installation:
# 
# - Requires AuthMe reloaded working with MySQL, this plugin relies on external authentication
# - To allow querying existing users, copy MySQL AuthMe configurations to DataSource section below in this file
# - Create EnderMail tables in same database as AuthMe, according recent configured parameters
# - Edit the line shown below in AuthMe config.yml to do unread mail and welcome message checks on player login:
#     forceCommands: [mail check quiet]
# - Once configurations were done in both plugins, restart the server
# 
# MySQL tables creation:
# 
# CREATE TABLE `endermail_messages` (
# 	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
# 	`mfrom` TEXT NOT NULL,
# 	`mto` TEXT NOT NULL,
# 	`sent` DATETIME NOT NULL,
# 	`subject` TEXT NOT NULL,
# 	`brief` TEXT NOT NULL,
# 	`message` TEXT NOT NULL,
# 	`attachment` TEXT NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 
# CREATE TABLE `endermail_folders` (
# 	`muser` TEXT NOT NULL,
# 	`folder` TINYINT UNSIGNED NOT NULL,
# 	`unread` TINYINT UNSIGNED NOT NULL,
# 	`id` INT UNSIGNED NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 


# edit these configurations copying them from AuthMe config.yml
DataSource:
  mySQLHost: localhost
  mySQLPort: 3306
  mySQLDatabase: authme
  mySQLUsername: authme
  mySQLPassword: 12345
  mySQLTablename: authme
  mySQLRealName: playername
  mySQLColumnLastLogin: lastlogin


# ticks in which plugin will remember last folder, message or entered line,
# for browsing, viewing and composing (default 2400 = 2min)
expire: 2400


# welcome message, from admin to new players with no messages in any folder (some folders cannot be emptied)
# available variable: %P = new player, triggered on login so requires proper installation documented on top
welcomeMessage:
  # if not enabled this entire section will be skipped
  enabled: false
  # optional single server console command triggered before sending welcome message
  # examples: op %P, "give %P diamond_block 64", say Welcome %P!, otherPlugin someParameter
  executeCommand: 
  # short message subject
  subject: Welcome to our server
  # message body, for correct visualization try not to exceed 9 lines and 53 chars by line
  body: |
    Hi %P, welcome to our server.
    Enjoy to play but respecting the rules,
    please visit our web page, thanks.
