# 
# EnderMail installation:
# 
# - Requires AuthMe working with MySQL, a plugin like this would have no sense without authentication
# - Create EnderMail tables in same database as AuthMe for access on querying existing users
# - Copy MySQL AuthMe configurations to datasource section below in this file for same reason
# - Edit this line in AuthMe config.yml to do a mail check on players login:
# 
# forceCommands: [mail check quiet]
# 
# 
# MySQL tables creation:
# 
# CREATE TABLE `endermail_messages` (
# 	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
# 	`mfrom` TEXT NOT NULL,
# 	`mto` TEXT NOT NULL,
# 	`sent` DATETIME NOT NULL,
# 	`subject` TEXT NOT NULL,
# 	`brief` TEXT NOT NULL,
# 	`message` TEXT NOT NULL,
# 	`attachment` TEXT NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 
# CREATE TABLE `endermail_folders` (
# 	`muser` TEXT NOT NULL,
# 	`folder` TINYINT UNSIGNED NOT NULL,
# 	`unread` TINYINT UNSIGNED NOT NULL,
# 	`id` INT UNSIGNED NOT NULL)
# COLLATE='latin1_swedish_ci' ENGINE=InnoDB;
# 
# 
# A message to the server admin (my colleague)
# 
# hi, i hope you enjoy this plugin and contact me at project page http://dev.bukkit.org/bukkit-plugins/endermail/
# if have some bug report or suggestion, thanks for using this plugin and happy crafting
# 


# edit these configurations copying from AuthMe config.yml
DataSource:
  mySQLHost: localhost
  mySQLPort: 3306
  mySQLDatabase: database
  mySQLUsername: dbuser
  mySQLPassword: dbpass
  mySQLTablename: table
  mySQLRealName: playername
  mySQLColumnLastLogin: lastlogin

# ticks in which plugin will remember last folder, message or entered line,
# for browsing, viewing and composing (default 2400 = 2min)
expire: 2400
